

-- ----------------------------
-- Table structure for TL_RULE_DEFINE
-- ----------------------------
DROP TABLE "TL_RULE_DEFINE";
CREATE TABLE "TL_RULE_DEFINE" (
"ITEM_NO" NVARCHAR2(32) NOT NULL ,
"CONTENT" NVARCHAR2(256) NULL ,
"EXE_SQL" NVARCHAR2(512) NULL ,
"EXE_CLASS" NVARCHAR2(128) NULL ,
"PARAM_NAME" NVARCHAR2(128) NULL ,
"PARAM_TYPE" NVARCHAR2(128) NULL ,
"COMPARISON_CODE" NVARCHAR2(32) NULL ,
"COMPARISON_VALUE" NVARCHAR2(64) NULL ,
"BASELINE" NVARCHAR2(64) NULL ,
"RESULT" NVARCHAR2(6) NULL ,
"PRIORITY" NVARCHAR2(32) NULL ,
"CONTINUE_FLAG" NVARCHAR2(2) NULL ,
"PARENT_ITEM_NO" NVARCHAR2(2) NULL ,
"PARENT_EXPRESS" NVARCHAR2(256) NULL ,
"EXECUTOR" NVARCHAR2(64) NULL ,
"REMARK" NVARCHAR2(64) NULL ,
"COMMENTS" NVARCHAR2(64) NULL ,
"ENABLE_FLAG" NVARCHAR2(2) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"UPDATE_TIME" TIMESTAMP(6)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "TL_RULE_DEFINE" IS '规则引擎定义表';
COMMENT ON COLUMN "TL_RULE_DEFINE"."ITEM_NO" IS '主key';
COMMENT ON COLUMN "TL_RULE_DEFINE"."CONTENT" IS '中文的内容说明';
COMMENT ON COLUMN "TL_RULE_DEFINE"."EXE_SQL" IS '执行的SQL语句';
COMMENT ON COLUMN "TL_RULE_DEFINE"."EXE_CLASS" IS '执行检查的java类名， 与exe_sql二者只填写一项';
COMMENT ON COLUMN "TL_RULE_DEFINE"."PARAM_NAME" IS 'SQL语句的参数,多个参数用,分割，读值时需要完成和继承DefaultCustomerCheck类。';
COMMENT ON COLUMN "TL_RULE_DEFINE"."PARAM_TYPE" IS 'exe_sql或者exe_class的参数类型，多个类型用逗号（,）分割，与param_name需一一对应。';
COMMENT ON COLUMN "TL_RULE_DEFINE"."COMPARISON_CODE" IS '01: = ，  02: > ， 03 : < ， 04 != ， 05 >= ， 06: <= ， 07 include ， 08 exclude ， 09: included by 10: excluded by  11: equal , 12 : not equal 13: euqalIngoreCase 15: matches 16: NOT MATCHES';
COMMENT ON COLUMN "TL_RULE_DEFINE"."COMPARISON_VALUE" IS '=,>,<,>=,<=, !=, include, exclude等内容。';
COMMENT ON COLUMN "TL_RULE_DEFINE"."BASELINE" IS '参数值，比较目标值';
COMMENT ON COLUMN "TL_RULE_DEFINE"."RESULT" IS '1 - 通过  2 - 关注 3 -拒绝  逻辑运算满足目标值的时候读取改内容。';
COMMENT ON COLUMN "TL_RULE_DEFINE"."PRIORITY" IS '执行的优先顺序，值大的优先执行.';
COMMENT ON COLUMN "TL_RULE_DEFINE"."CONTINUE_FLAG" IS '是否继续执行下一条，如果某条规则满足中断的话，那么就设置为 2. 1 -- 继续  2 -- 中断';
COMMENT ON COLUMN "TL_RULE_DEFINE"."PARENT_ITEM_NO" IS '如果是子规则，那么需要填写父规则的item_no';
COMMENT ON COLUMN "TL_RULE_DEFINE"."PARENT_EXPRESS" IS '同一PARENT_ITEM的各个ITEM的运算表达式。 ( A AND B OR C)';
COMMENT ON COLUMN "TL_RULE_DEFINE"."EXECUTOR" IS '结果执行后的被执行体，从AbstractCommand中继承下来。';
COMMENT ON COLUMN "TL_RULE_DEFINE"."ENABLE_FLAG" IS '是否使用 1 - 有效  2 - 失效';

-- ----------------------------
-- Checks structure for table TL_RULE_DEFINE
-- ----------------------------
ALTER TABLE "TL_RULE_DEFINE" ADD CHECK ("ITEM_NO" IS NOT NULL);
